// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using OPS.DAL.Infrastructure.Filters.Abstract;

namespace OPS.DAL.Infrastructure.Filters.Concrete
{
    public class OrderJoin<T, TQ> : IOrderJoin<T, TQ> where T : IOrderContext
    {
        private readonly T _t;
        private readonly TQ _q;

        internal OrderJoin(T t, TQ q)
        {
            _t = t;
            _q = q;
        }

        public T And { get { _t.And(); return _t; } }

        public TQ Order()
        {
            return _q;
        }
    }
}

