// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Data;

namespace OPS.DAL.Infrastructure.Interfaces
{
    /// <summary>
    /// This is a provider which should be used to give the
    /// target connection string to the context, this should be
    /// implemented inside the applicaiton.
    /// </summary>
    public interface IConnectionStringProvider
    {
        /// <summary>
        /// Get the target connection string
        /// </summary>
        /// <returns>The connection string</returns>
        string GetConnectionString();
    }
}

