// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Data;

namespace OPS.DAL.Infrastructure.Interfaces
{
	/// <summary>
    /// A system wide context that holds the connection to the database and manages the connection
    /// </summary>
	public interface IDBContext
	{
	      /// <summary>
          /// Connection to the database
          /// </summary>
		  IDbConnection Connection { get; }
      
          /// <summary>
          /// Creates a new unit of work for this context
          /// </summary>
          /// <returns>A new unit of work</returns>
          IUnitOfWork Unit();
	}
}

