// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using OPS.DAL.Infrastructure.Models.Concrete;

namespace OPS.DAL.Infrastructure.Interfaces
{
    /// <summary>
    /// Type of an operation
    /// </summary>
    public enum OperationType
    {
        Add = 1,
        Remove = 2,
        Update = 3
    }

    /// <summary>
    /// A database operation
    /// </summary>
	public interface IOperation
    {
        OperationType Type { get; }
        BaseModel Object { get; }
    }
}

