// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


namespace OPS.DAL.Infrastructure.Filters.Abstract
{

    /// <summary>
    /// Holds a filter to be applied on an attribute
    /// </summary>
    public interface IPropertyFilter
    {
        /// <summary>
        /// The property name to apply the filter
        /// </summary>
        string PropertyName { get; set; }

        /// <summary>
        /// Expression type
        /// </summary>
        string Type { get; set; }
            
        /// <summary>
        /// Value if available
        /// </summary>
        object Value { get; set; }
    }
}

