// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace OPS.DAL.Dapper
{
    public static partial class SqlMapper
    {
        /// <summary>
        /// Dummy type for excluding from multi-map
        /// </summary>
        private class DontMap { /* hiding constructor */ }
    }
}


