// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Collections.Generic;
using OPS.DAL.Infrastructure.Models.Concrete;

namespace OPS.DAL.Infrastructure.Collections.Abstract
{
    /// <summary>
    /// Collection of data models retrieved from an object. as a reference collection
    /// </summary>
    /// <typeparam name="T">Type of object</typeparam>
    public interface IReferencedEntityCollection<T> : IEnumerable<T> where T: BaseModel
	  {
      /// <summary>
      /// Add an object to the collection. this will also update the parent objects related value which the collection is retrieved from. this will not add this object to the data source.
      /// </summary>
      /// <param name="entityToAdd">entity to add </param>
      void Add(T entityToAdd);
	  }
}


