// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using OPS.DAL.Infrastructure.Filters.Abstract;

namespace OPS.DAL.Infrastructure.Models.Abstract.Context
{

    /// <summary>
    /// Helps to build order for queries on the data source Order
    /// </summary>
    public interface IOrderOrderContext: IOrderContext
    {

		/// <summary>
		///  Apply order by on ID attribute . this order by expression will be preserved within entire query context
		/// </summary>
		IOrderElement<IOrderOrderContext,IOrderQueryContext> ID { get; }

		/// <summary>
		///  Apply order by on Quantity attribute . this order by expression will be preserved within entire query context
		/// </summary>
		IOrderElement<IOrderOrderContext,IOrderQueryContext> Quantity { get; }

		/// <summary>
		///  Apply order by on Remarks attribute . this order by expression will be preserved within entire query context
		/// </summary>
		IOrderElement<IOrderOrderContext,IOrderQueryContext> Remarks { get; }



    }
}
