// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using OPS.DAL.Infrastructure.Filters.Abstract;

namespace OPS.DAL.Infrastructure.Models.Abstract.Context
{

  /// <summary>
  /// Helps to build filters for queries on the data source Order
  /// </summary>
	public interface IOrderFilterContext : IFilterContext
	{


		/// <summary>
		///  Apply filters on ID attribute . these filters will be preserved within entire query context
		/// </summary>
		INumberFilter<IOrderFilterContext,IOrderQueryContext> ID { get; }


		/// <summary>
		///  Apply filters on Quantity attribute . these filters will be preserved within entire query context
		/// </summary>
		INumberFilter<IOrderFilterContext,IOrderQueryContext> Quantity { get; }


		/// <summary>
		///  Apply filters on Remarks attribute . these filters will be preserved within entire query context
		/// </summary>
	    IStringFilter<IOrderFilterContext,IOrderQueryContext> Remarks { get; }



        /// <summary>
        /// Start Parenthesizes
        /// </summary>
        IOrderFilterContext Start { get; }

        /// <summary>
        /// Start Parenthesizes
        /// </summary>
        IOrderFilterContext End { get; }

    }
}
