// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System;
using OPS.DAL.Infrastructure.Actions.Abstract;

namespace OPS.DAL.Infrastructure.Actions.Concrete
{
    internal class AddAction: IAddAction
    {
        private readonly Action<object> _action;
        private readonly object _parameter;

        internal AddAction(Action<object> action, object parameter )
        {
            _action = action;
            _parameter = parameter;
        }

        public void Run()
        {
            if(_action == null || _parameter ==null)
            { return; }
            _action(_parameter);
        }
    }
}
