// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Data;
using MySql.Data.MySqlClient;
using OPS.DAL.Infrastructure.Interfaces;

namespace OPS.DAL.Infrastructure
{
	/// <summary>
    /// An Implementation that uses MySqlConnection
    /// </summary>
	public class DBContext : IDBContext
    {
        private readonly string _connectionString;
        private IDbConnection _connection;

		/// <summary>
        /// Initialize  a new dapper context 
        /// </summary>
        public DBContext(IConnectionStringProvider connectionStringProvider)
        {
            _connectionString = connectionStringProvider.GetConnectionString();
        }

    	/// <summary>
        /// Get the connection to the database
        /// </summary>
        public IDbConnection Connection => _connection ?? (_connection = new MySqlConnection(_connectionString));

        public IUnitOfWork Unit() 
        {
            return new UnitOfWork(this);
        }
    }
}

