// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using OPS.DAL.Infrastructure.Interfaces;
using OPS.DAL.Infrastructure.Models.Concrete;

namespace OPS.DAL.Infrastructure
{
    internal class Operation : IOperation
    {
        internal Operation(OperationType type, BaseModel model)
        {
            Type = type;
            Object = model;
        }

        public OperationType Type { get; }
        public BaseModel Object { get; }
    }
}

